


SELECT
    ES.IDPRODUTO
    , ES.IDSUBPRODUTO
    , PG.DESCRRESPRODUTO
    , SUM (QTDCOMPRA) AS QTDCOMPRA
    , (
        (SUM (ES.QTDENTRAESTOQUE) - SUM (QTDCOMPRA)) - SUM (QTDDEVVENDA) 
    ) AS QTDOUTRASENTRADAS
    , SUM (QTDDEVCOMPRA) AS QTDDEVCOMPRA
    , SUM (QTDVENDA) AS QTDVENDA
    , SUM (QTDDEVVENDA) AS QTDDEVVENDA
    , RESERVA.QTDDISPONIVEL
    , SALDOINICIAL.QTDSALDOINICIAL
    , SALDOFINAL.QTDSALDOFINAL AS QTDATUALESTOQUE
    , RESERVA.QTDSALDORESERVA
    , SECAO.IDSECAO
    , SECAO.DESCRSECAO
    , GRUPO.IDGRUPO
    , GRUPO.DESCRGRUPO
    , SUBGRUPO.IDSUBGRUPO
    , SUBGRUPO.DESCRSUBGRUPO 
FROM
    (
        SELECT
            ESTOQUE_SINTETICO.IDPRODUTO
            , ESTOQUE_SINTETICO.IDSUBPRODUTO
            , SUM (ESTOQUE_SINTETICO.QTDSALDOINICIAL) AS QTDSALDOINICIAL 
        FROM
            ESTOQUE_SINTETICO 
        WHERE
            DTMOVIMENTO = 
                (
                    SELECT
                        MIN(DTMOVIMENTO) 
                    FROM
                        ESTOQUE_SINTETICO AS ESTOQUE 
                    WHERE
                        ESTOQUE_SINTETICO.IDPRODUTO = ESTOQUE.IDPRODUTO 
                        AND ESTOQUE_SINTETICO.IDSUBPRODUTO = ESTOQUE.IDSUBPRODUTO 
                        AND ESTOQUE_SINTETICO.IDEMPRESA IN (:RA_IDEMPRESA)
                        AND ESTOQUE_SINTETICO.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM 
                )
        GROUP BY
            ESTOQUE_SINTETICO.IDPRODUTO
            , ESTOQUE_SINTETICO.IDSUBPRODUTO 
    ) AS SALDOINICIAL 
    JOIN
        (
            SELECT
                ESTOQUE_SINTETICO.IDPRODUTO
                , ESTOQUE_SINTETICO.IDSUBPRODUTO
                , SUM (ESTOQUE_SINTETICO.QTDATUALESTOQUE) AS QTDSALDOFINAL 
            FROM
                ESTOQUE_SINTETICO 
            WHERE
                DTMOVIMENTO = 
                    (
                        SELECT
                            MAX(DTMOVIMENTO) 
                        FROM
                            ESTOQUE_SINTETICO AS ESTOQUE 
                        WHERE
                            ESTOQUE_SINTETICO.IDPRODUTO = ESTOQUE.IDPRODUTO 
                            AND ESTOQUE_SINTETICO.IDSUBPRODUTO = ESTOQUE.IDSUBPRODUTO 
                            AND ESTOQUE_SINTETICO.IDEMPRESA IN (:RA_IDEMPRESA)
                            AND ESTOQUE_SINTETICO.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM 
                    )
            GROUP BY
                ESTOQUE_SINTETICO.IDPRODUTO
                , ESTOQUE_SINTETICO.IDSUBPRODUTO 
        ) AS SALDOFINAL 
        ON (SALDOINICIAL.IDPRODUTO = SALDOFINAL.IDPRODUTO 
        AND SALDOINICIAL.IDSUBPRODUTO = SALDOFINAL.IDSUBPRODUTO) 
    JOIN
        (
            SELECT
                IDPRODUTO
                , IDSUBPRODUTO
                , SUM (QTDSALDORESERVA) AS QTDSALDORESERVA
                , SUM (QTDDISPONIVEL) AS QTDDISPONIVEL 
            FROM
                PRODUTOS_SALDOS_VIEW PV 
            WHERE
                1 = 1 
                AND PV.IDEMPRESA IN (:RA_IDEMPRESA)
                AND PV.IDPRODUTO IN (:RA_IDSUBPRODUTO)
                AND 1 = 1 
            GROUP BY
                PV.IDPRODUTO
                , PV.IDSUBPRODUTO 
        ) AS RESERVA 
        ON (SALDOFINAL.IDPRODUTO = RESERVA.IDPRODUTO 
        AND SALDOFINAL.IDSUBPRODUTO = RESERVA.IDSUBPRODUTO) 
    JOIN
        ESTOQUE_SINTETICO AS ES 
        ON (RESERVA.IDPRODUTO = ES.IDPRODUTO 
        AND RESERVA.IDSUBPRODUTO = ES.IDSUBPRODUTO) 
    JOIN
        PRODUTO_GRADE AS PG 
        ON (ES.IDPRODUTO = PG.IDPRODUTO 
        AND ES.IDSUBPRODUTO = PG.IDSUBPRODUTO) 
    JOIN
        PRODUTO 
        ON (PG.IDPRODUTO = PRODUTO.IDPRODUTO) 
    JOIN
        SECAO 
        ON (PRODUTO.IDSECAO = SECAO.IDSECAO) 
    JOIN
        GRUPO 
        ON (PRODUTO.IDGRUPO = GRUPO.IDGRUPO) 
    JOIN
        SUBGRUPO 
        ON (PRODUTO.IDSUBGRUPO = SUBGRUPO.IDSUBGRUPO) 
WHERE
    1 = 1 
    AND ES.IDEMPRESA IN (:RA_IDEMPRESA)
    AND ES.IDLOCALESTOQUE IN (:RA_IDLOCALESTOQUE)
    AND GRUPO.IDGRUPO IN (:RA_IDGRUPO)
    AND SUBGRUPO.IDSUBGRUPO IN (:RA_IDSUBGRUPO)
    AND SECAO.IDSECAO IN (:RA_IDSECAO)
    AND ES.IDSUBPRODUTO IN (:RA_IDSUBPRODUTO)
    AND ES.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM 
    AND 1 = 1 
GROUP BY
    ES.IDPRODUTO
    , ES.IDSUBPRODUTO
    , PG.DESCRRESPRODUTO
    , SECAO.IDSECAO
    , SECAO.DESCRSECAO
    , GRUPO.IDGRUPO
    , GRUPO.DESCRGRUPO
    , SUBGRUPO.IDSUBGRUPO
    , SUBGRUPO.DESCRSUBGRUPO
    , SALDOINICIAL.QTDSALDOINICIAL
    , SALDOFINAL.QTDSALDOFINAL
    , RESERVA.QTDSALDORESERVA
    , RESERVA.QTDDISPONIVEL