

SELECT
    TMP3.IDEMPRESA,
    TMP3.IDLOCALESTOQUE,
    TMP3.IDFORNECEDOR,
    TMP3.NOMEFORNECEDOR,
    TMP3.IDPRODUTO,
    TMP3.IDSUBPRODUTO,
    TMP3.DESCRRESPRODUTO,
    TMP3.IDSECAO,
    TMP3.DESCRSECAO,
    TMP3.IDGRUPO,
    TMP3.DESCRGRUPO,
    TMP3.IDSUBGRUPO,
    TMP3.DESCRSUBGRUPO,
    TMP3.VALVENDAMES1,
    TMP3.VALVENDAMES2,
    TMP3.VALVENDAMES3,
    TMP3.VALVENDAMES4,
    TMP3.VALVENDAMES5,
    TMP3.VALVENDAMES6,
    TMP3.VALMEDIA,
    TMP3.QTDPEDIDO,
    CAST (SUM (ESA.QTDATUALESTOQUE) AS DECIMAL (12,3)) AS QTDATUALESTOQUE,
    TMP3.DIASESTOQUE,
    TMP3.DIASENTREGA,
    TMP3.ESTOQUEIDEAL,
    TMP3.PONTOCRITICOPEDIDO,
    TMP3.ESTOQUEIDEAL - TMP3.QTDPEDIDO AS SUGESTAODECOMPRAS
FROM
    (
    SELECT
        TMP2.IDEMPRESA,
        TMP2.IDLOCALESTOQUE,
        CF.IDCLIFOR AS IDFORNECEDOR,
        CF.NOME AS NOMEFORNECEDOR,
        TMP2.IDPRODUTO,
        TMP2.IDSUBPRODUTO,
        TMP2.DESCRRESPRODUTO,
        TMP2.IDSECAO,
        TMP2.DESCRSECAO,
        TMP2.IDGRUPO,
        TMP2.DESCRGRUPO,
        TMP2.IDSUBGRUPO,
        TMP2.DESCRSUBGRUPO,
        TMP2.VALVENDAMES1,
        TMP2.VALVENDAMES2,
        TMP2.VALVENDAMES3,
        TMP2.VALVENDAMES4,
        TMP2.VALVENDAMES5,
        TMP2.VALVENDAMES6,
        TMP2.VALTOTAL,
        CAST ((TMP2.VALTOTAL / 6) AS DECIMAL (12,3)) VALMEDIA,
        COALESCE ((
        SELECT
            SUM (PCP.QTDSOLICITADA) - SUM (PCP.QTDATENDIDA)
        FROM
            DBA.PEDIDO_COMPRA_PROD PCP
        WHERE
            PCP.IDEMPRESA = TMP2.IDEMPRESA AND
            PCP.IDPRODUTO = TMP2.IDPRODUTO AND
            PCP.IDSUBPRODUTO = TMP2.IDSUBPRODUTO
        ),0) AS QTDPEDIDO,
        COALESCE (PC.DIASESTOQUE,0) AS DIASESTOQUE,
        CF.DIASENTREGA,
        CAST (CAST (TMP2.VALTOTAL / 180 AS DECIMAL (12,3)) * CAST ((COALESCE (PC.DIASESTOQUE,0) + CF.DIASENTREGA) AS DECIMAL (12,3)) AS DECIMAL (12,3)) AS ESTOQUEIDEAL,
        CAST (
            CASE
                WHEN CF.DIASENTREGA = 0 THEN
                    0
                ELSE
                    CAST (TMP2.VALTOTAL / 6 AS DECIMAL (12,3)) * CAST (COALESCE (PC.DIASESTOQUE,0) / CF.DIASENTREGA AS DECIMAL (12,3))
            END
        AS DECIMAL (12,3)) AS PONTOCRITICOPEDIDO
    FROM
        (
        SELECT
            TMP.IDEMPRESA,
            TMP.IDLOCALESTOQUE,
            TMP.IDPRODUTO,
            TMP.IDSUBPRODUTO,
            TMP.DESCRRESPRODUTO,
            TMP.IDSECAO,
            TMP.DESCRSECAO,
            TMP.IDGRUPO,
            TMP.DESCRGRUPO,
            TMP.IDSUBGRUPO,
            TMP.DESCRSUBGRUPO,
            CAST (SUM (TMP.VALVENDAMES1) AS DECIMAL (12,3)) AS VALVENDAMES1,
            CAST (SUM (TMP.VALVENDAMES2) AS DECIMAL (12,3)) AS VALVENDAMES2,
            CAST (SUM (TMP.VALVENDAMES3) AS DECIMAL (12,3)) AS VALVENDAMES3,
            CAST (SUM (TMP.VALVENDAMES4) AS DECIMAL (12,3)) AS VALVENDAMES4,
            CAST (SUM (TMP.VALVENDAMES5) AS DECIMAL (12,3)) AS VALVENDAMES5,
            CAST (SUM (TMP.VALVENDAMES6) AS DECIMAL (12,3)) AS VALVENDAMES6,
            CAST ((SUM (TMP.VALVENDAMES1) + SUM (TMP.VALVENDAMES2) + SUM (TMP.VALVENDAMES3) + SUM (TMP.VALVENDAMES4) + SUM (TMP.VALVENDAMES5) + SUM (TMP.VALVENDAMES6)) AS DECIMAL (12,3)) AS VALTOTAL
        FROM
            (
            SELECT
                ES.IDEMPRESA,
                ES.IDLOCALESTOQUE,
                ES.IDPRODUTO,
                ES.IDSUBPRODUTO,
                PV.DESCRRESPRODUTO,
                PV.IDSECAO,
                S.DESCRSECAO,
                PV.IDGRUPO,
                G.DESCRGRUPO,
                PV.IDSUBGRUPO,
                SG.DESCRSUBGRUPO,
                CASE
                    WHEN PV.TIPOBAIXAMESTRE = 'M' THEN
                        ES.IDPRODUTO
                    ELSE
                        ES.IDSUBPRODUTO
                END AS JOINESA,
                MONTH (ES.DTMOVIMENTO) AS MES,
                CASE
                    WHEN MONTH (ES.DTMOVIMENTO) = MONTH (DBA.UF_DTINI_MES(CURRENT DATE - 1 MONTH)) THEN
                        SUM (ES.QTDVENDA) - SUM (ES.QTDDEVVENDA)
                    ELSE
                        0
                END AS VALVENDAMES1,
                CASE
                    WHEN MONTH (ES.DTMOVIMENTO) = MONTH (DBA.UF_DTINI_MES(CURRENT DATE - 2 MONTH)) THEN
                        SUM (ES.QTDVENDA) - SUM (ES.QTDDEVVENDA)
                    ELSE
                        0
                END AS VALVENDAMES2,
                CASE
                    WHEN MONTH (ES.DTMOVIMENTO) = MONTH (DBA.UF_DTINI_MES(CURRENT DATE - 3 MONTH)) THEN
                        SUM (ES.QTDVENDA) - SUM (ES.QTDDEVVENDA)
                    ELSE
                        0
                END AS VALVENDAMES3,
                CASE
                    WHEN MONTH (ES.DTMOVIMENTO) = MONTH (DBA.UF_DTINI_MES(CURRENT DATE - 4 MONTH)) THEN
                        SUM (ES.QTDVENDA) - SUM (ES.QTDDEVVENDA)
                    ELSE
                        0
                END AS VALVENDAMES4,
                CASE
                    WHEN MONTH (ES.DTMOVIMENTO) = MONTH (DBA.UF_DTINI_MES(CURRENT DATE - 5 MONTH)) THEN
                        SUM (ES.QTDVENDA) - SUM (ES.QTDDEVVENDA)
                    ELSE
                        0
                END AS VALVENDAMES5,
                CASE
                    WHEN MONTH (ES.DTMOVIMENTO) = MONTH (DBA.UF_DTINI_MES(CURRENT DATE - 6 MONTH)) THEN
                        SUM (ES.QTDVENDA) - SUM (ES.QTDDEVVENDA)
                    ELSE
                        0
                END AS VALVENDAMES6
            FROM
                DBA.PRODUTOS_VIEW PV
                JOIN DBA.ESTOQUE_SINTETICO ES ON
                    ES.IDPRODUTO = PV.IDPRODUTO AND
                    ES.IDSUBPRODUTO = PV.IDSUBPRODUTO
                JOIN DBA.SECAO S ON
                    PV.IDSECAO = S.IDSECAO
                JOIN DBA.GRUPO G ON
                    PV.IDGRUPO = G.IDGRUPO
                JOIN DBA.SUBGRUPO SG ON
                    PV.IDSUBGRUPO = SG.IDSUBGRUPO
            WHERE
                ES.DTMOVIMENTO BETWEEN DBA.UF_DTINI_MES(CURRENT DATE - 6 MONTH) AND DBA.UF_DTINI_MES(CURRENT DATE - 1 MONTH) AND
                ES.IDEMPRESA IN (:RA_IDEMPRESA)
            GROUP BY
                ES.IDEMPRESA,
                ES.IDLOCALESTOQUE,
                ES.IDSUBPRODUTO,
                ES.IDPRODUTO,
                PV.TIPOBAIXAMESTRE,
                PV.DESCRRESPRODUTO,
                PV.IDSECAO,
                S.DESCRSECAO,
                PV.IDGRUPO,
                G.DESCRGRUPO,
                PV.IDSUBGRUPO,
                SG.DESCRSUBGRUPO,
                MONTH (ES.DTMOVIMENTO)
            ) AS TMP
        GROUP BY
            TMP.IDEMPRESA,
            TMP.IDLOCALESTOQUE,
            TMP.IDSUBPRODUTO,
            TMP.IDPRODUTO,
            TMP.DESCRRESPRODUTO,
            TMP.IDSECAO,
            TMP.DESCRSECAO,
            TMP.IDGRUPO,
            TMP.DESCRGRUPO,
            TMP.IDSUBGRUPO,
            TMP.DESCRSUBGRUPO
        ) AS TMP2
        JOIN DBA.PRODUTO_FORNECEDOR PF ON
            PF.IDPRODUTO = TMP2.IDPRODUTO AND
            PF.IDSUBPRODUTO = TMP2.IDSUBPRODUTO
        JOIN DBA.CLIENTE_FORNECEDOR CF ON
            CF.IDCLIFOR = PF.IDCLIFOR
        LEFT JOIN DBA.PRODUTO_COMPRAS PC ON
            PC.IDPRODUTO = TMP2.IDPRODUTO AND
            PC.IDSUBPRODUTO = TMP2.IDSUBPRODUTO AND
            PC.IDEMPRESA = TMP2.IDEMPRESA
    ) AS TMP3
    JOIN DBA.ESTOQUE_SALDO_ATUAL ESA ON
        TMP3.IDEMPRESA = ESA.IDEMPRESA AND
        TMP3.IDLOCALESTOQUE = ESA.IDLOCALESTOQUE AND
        TMP3.IDPRODUTO = ESA.IDPRODUTO AND
        TMP3.IDSUBPRODUTO = ESA.IDSUBPRODUTO
GROUP BY
    TMP3.IDEMPRESA,
    TMP3.IDLOCALESTOQUE,
    TMP3.IDFORNECEDOR,
    TMP3.NOMEFORNECEDOR,
    TMP3.IDPRODUTO,
    TMP3.IDSUBPRODUTO,
    TMP3.DESCRRESPRODUTO,
    TMP3.IDSECAO,
    TMP3.DESCRSECAO,
    TMP3.IDGRUPO,
    TMP3.DESCRGRUPO,
    TMP3.IDSUBGRUPO,
    TMP3.DESCRSUBGRUPO,
    TMP3.VALVENDAMES1,
    TMP3.VALVENDAMES2,
    TMP3.VALVENDAMES3,
    TMP3.VALVENDAMES4,
    TMP3.VALVENDAMES5,
    TMP3.VALVENDAMES6,
    TMP3.VALMEDIA,
    TMP3.QTDPEDIDO,
    TMP3.DIASESTOQUE,
    TMP3.DIASENTREGA,
    TMP3.ESTOQUEIDEAL,
    TMP3.PONTOCRITICOPEDIDO

